export const purpleTheme = {
	name: "purple",
	colors: {
		backgroundGradient: "linear-gradient(to bottom left, #252525, #0C0C0C)",
		backgroundRadial: "radial-gradient(ellipse at center, #2e2e2e, #0C0C0C)",
		background: "#000",
		backgroundSecondary: "#272727",
		branding: "#fa2ac1",
		title: "#fff",
		inactiveTitle: "#8b8b8b",
		subtitle: "#ccc",
		body: "#ccc",
		contrastText: "#2b2b2b",
		caption: "#ccc",
		icon: "#fff",
		iconHover: "#ccc",
		button: "",
		shadow: "",
	},
	fontSizes: {
		xs: "12px",
		sm: "14px",
		md: "16px",
		lg: "18px",
		xl: "20px",
	},
};

//FFA6A6
export const redTheme = {
	name: "red",
	colors: {
		backgroundGradient: "linear-gradient(to bottom left, #252525, #0C0C0C)",
		backgroundRadial: "radial-gradient(ellipse at center, #2e2e2e, #0C0C0C)",
		background: "#000",
		backgroundSecondary: "#272727",
		branding: "#c73232",
		title: "#fff",
		inactiveTitle: "#8b8b8b",
		subtitle: "#ccc",
		body: "#ccc",
		contrastText: "#2b2b2b",
		caption: "#ccc",
		icon: "#fff",
		iconHover: "#ccc",
		button: "",
		shadow: "",
	},
	fontSizes: {
		xs: "12px",
		sm: "14px",
		md: "16px",
		lg: "18px",
		xl: "20px",
	},
};

//14e0d3
export const lightBlueTheme = {
	name: "lightBlue",
	colors: {
		backgroundGradient: "linear-gradient(to bottom left, #252525, #0C0C0C)",
		backgroundRadial: "radial-gradient(ellipse at center, #2e2e2e, #0C0C0C)",
		background: "#000",
		backgroundSecondary: "#272727",
		branding: "#14e0d3",
		title: "#fff",
		inactiveTitle: "#8b8b8b",
		subtitle: "#ccc",
		body: "#ccc",
		contrastText: "#2b2b2b",
		caption: "#ccc",
		icon: "#fff",
		iconHover: "#ccc",
		button: "",
		shadow: "",
	},
	fontSizes: {
		xs: "12px",
		sm: "14px",
		md: "16px",
		lg: "18px",
		xl: "20px",
	},
};

export const greenTheme = {
	name: "green",
	colors: {
		name: "green",
		backgroundGradient: "linear-gradient(to bottom left, #252525, #0C0C0C)",
		backgroundRadial: "radial-gradient(ellipse at center, #2e2e2e, #0C0C0C)",
		background: "#000",
		backgroundSecondary: "#272727",
		branding: "#00ff84",
		title: "#fff",
		inactiveTitle: "#8b8b8b",
		subtitle: "#ccc",
		body: "#ccc",
		contrastText: "#2b2b2b",
		caption: "#ccc",
		icon: "#fff",
		iconHover: "#ccc",
		button: "",
		shadow: "",
	},
	fontSizes: {
		xs: "12px",
		sm: "14px",
		md: "16px",
		lg: "18px",
		xl: "20px",
	},
};

export const orangeTheme = {
	name: "orange",
	colors: {
		backgroundGradient: "linear-gradient(to bottom left, #252525, #0C0C0C)",
		backgroundRadial: "radial-gradient(ellipse at center, #2e2e2e, #0C0C0C)",
		background: "#000",
		backgroundSecondary: "#272727",
		branding: "#fa8c05",
		title: "#fff",
		inactiveTitle: "#8b8b8b",
		subtitle: "#ccc",
		body: "#ccc",
		contrastText: "#2b2b2b",
		caption: "#ccc",
		icon: "#fff",
		iconHover: "#9b883c",
		button: "",
		shadow: "",
	},
	fontSizes: {
		xs: "12px",
		sm: "14px",
		md: "16px",
		lg: "18px",
		xl: "20px",
	},
};

export const darkYellowTheme = {
	name: "darkYellow",
	colors: {
		backgroundGradient: "linear-gradient(to left top, #252525, #0C0C0C)",
		backgroundRadial: "radial-gradient(ellipse at center, #2e2e2e, #0C0C0C)",
		background: "#000",
		backgroundSecondary: "#272727",
		branding: "#FCD434",
		title: "#fff",
		inactiveTitle: "#8b8b8b",
		subtitle: "#ccc",
		body: "#ccc",
		contrastText: "#2b2b2b",
		caption: "#ccc",
		icon: "#fff",
		iconHover: "#9b883c",
		button: "",
		shadow: "",
	},
	fontSizes: {
		xs: "12px",
		sm: "14px",
		md: "16px",
		lg: "18px",
		xl: "20px",
	},
};

export const lightTheme = {
	name: "light",
	colors: {
		backgroundGradient: "linear-gradient(202deg, #ffffff 0%, #e6e6e6 100%)",
		backgroundRadial: "radial-gradient(circle, #ffffff 0%, #e6e6e6 100%)",
		background: "#ffffff",
		backgroundSecondary: "#ddf0fa",
		branding: "#015077",
		title: "#015077",
		inactiveTitle: "#8b8b8b",
		subtitle: "#383838",
		body: "#474747",
		contrastText: "#2b2b2b",
		caption: "#ccc",
		icon: "#fff",
		iconHover: "#000000",
		button: "",
		shadow: "",
	},
	fontSizes: {
		xs: "12px",
		sm: "14px",
		md: "16px",
		lg: "18px",
		xl: "20px",
	},
};
