export const darkTheme = {
	name: "dark",
	colors: {
		imageBlur: "url('/img/bg_circle-dark.png')",
		backgroundPage: "#161616",
		backgroundPageRgb: [22, 22, 22],
		backgroundGradient: "linear-gradient(to left top, #252525, #0C0C0C)",
		backgroundRadial: "radial-gradient(ellipse at center, #2e2e2e, #0C0C0C)",
		background: "#000",
		backgroundSecondary: "#272727",
		branding: "#fec800",
		title: "#fff",
		inactiveTitle: "#8b8b8b",
		subtitle: "#ccc",
		body: "#ccc",
		contrastText: "#2b2b2b",
		caption: "#ccc",
		icon: "#fff",
		iconHover: "#9b883c",
		button: "",
		shadow: "",
	},
	fontSizes: {
		xs: "12px",
		sm: "14px",
		md: "16px",
		lg: "18px",
		xl: "20px",
	},
};

export const lightTheme = {
	name: "light",
	colors: {
		imageBlur: "url('/img/bg_circle-light.png')",
		backgroundPage: "#eeeeee",
		backgroundPageRgb: [238, 238, 238],
		backgroundGradient: "linear-gradient(202deg, #ffffff 0%, #e6e6e6 100%)",
		backgroundRadial: "radial-gradient(circle, #ffffff 0%, #e6e6e6 100%)",
		background: "#ffffff",
		backgroundSecondary: "#d3d3d3",
		branding: "#362f2f",
		title: "#362f2f",
		inactiveTitle: "#8b8b8b",
		subtitle: "#383838",
		body: "#666666",
		contrastText: "#2b2b2b",
		caption: "#ccc",
		icon: "#fff",
		iconHover: "#000000",
		button: "",
		shadow: "",
	},
	fontSizes: {
		xs: "12px",
		sm: "14px",
		md: "16px",
		lg: "18px",
		xl: "20px",
	},
};
